#! /bin/sh

### BEGIN INIT INFO
# Provides:		cjudge_server
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		
# Short-Description:	Open source judge server
### END INIT INFO

set -e

test -x /usr/sbin/cjudge_server || exit 0

./usr/sbin/cjudge_server &

exit 0
